config/routes.rb
Rails.application.routes.draw do
  root 'app#home'
  
  #get 'app/home'
  get '/basics' , to: "app#basics"
  get '/ruby' , to: "app#ruby"
  get '/git' , to: "app#git"
  get '/testing' , to: "app#testing"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/app_controller.rb
class AppController < ApplicationController
  def home
  end

  def basics
  end

  def ruby
  end

  def git
  end

  def testing
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def hello
        render html: "hello world!"
    end
end

app/helpers/app_helper.rb
module AppHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/app/basics.html.erb
<% provide(:title, "Basics") %>
<!DOCTYPE html>
<html>
    <head>
        <title><%= yield(:title) %> </title>
    </head>

    <body>
        <div class="center jumbotron">
            <br><h2 class="titulo">Basics</h2><br>

            <h3>¿Qué es un resource en el contexto de una aplicación web REST
            en Ruby on Rails?</h4>
                <p>Un "resource" o recurso es el término usado para una colección de objetos similares, como titulos, nombres o datos. 
                Puedes crear, leer, actualizar y eliminar objetos para un recurso y estas operaciones son referidas como operaciones CRUD</h3>
                <p>Rails incluye un método llamado resources que puedes utilizar para declarar un recurso REST estándar.</p>

            <h3>¿Qué puede hacerse con un resource?</h3>
                <p>Es un recurso que podemos utilizar para ahorrarnos lineas de codigo y seguir el principio "Don't Repeat Yourself" 
                (DRY o No te repitas).</p>

            <h3>¿Qué es RESTful routing?</h3>
                <p> RESTful routing es un estándar usado en muchos lenguajes de programación para crear rutas eficcientes y reusables y apunta a los metodos HTTP(GET, POST,PATCH, DELETE) y las acciones CRUD(Create, Read, Update, Delete).<br><br>
                Haciendo facil para otros desarrolladores entender y navegar la aplicación de una manera limpia y consistente.<br> <a href="https://www.youtube.com/watch?v=JD6VNRdGl98">Aqui lo explican en 5 minutos!</a></p>
                
            <h3>¿Cuántas acciones básicas tiene esta filosofía? ¿Cuáles son?</h3>

                <p>Esta filosofía cuenta con 7 acciones basicas., como son:<br>            
                    Index<br>  
                    Show<br>  
                    New<br>  
                    Create<br>  
                    Edit<br>  
                    Update<br>  
                    Destroy<br>  
                </p>

            <h3>¿Cuales verbos HTTP se utilizan en cada una de ellas?</h3>
                <p>
                Index -> GET<br>
                New -> GET<br>
                Create -> POST<br>
                Show -> GET<br>
                Edit -> GET<br>
                Update -> PATCH<br>
                Destroy -> DELETE<br>
            </p>
           
            <a href="/">Back to Home Page</a>
        </div>
    </body>
</html>

app/views/app/git.html.erb
<% provide(:title, "Git") %>
<!DOCTYPE html>
<html>
    <head>
        <title><%= yield(:title) %> </title>
    </head>

    <body>
        <div class="center jumbotron">
            <br><h2 class="titulo">Git</h2><br>

        <h3>Inicialización  de  un  repositorio  de  git  nuevo  en  una  aplicación existente.</h3>

            <p>Colocamos en la consola ubicados dentro de la carpeta de nuestra aplicación. </p>
            <pre> git init </pre>

        <h3>Creación de un branch nuevo.</h3>

            <p>Para crear un nuevo branch y cambiar a este usar el comando</p>
            <pre> git checkout -b new_branch_name </pre>

        <h3>Realizar un commit incluyendo todos los cambios actuales.</h3>

        <p>Para commitear todos los cambios actuales basta con <pre> git commit -a -m "comentario" </pre>, con este commando hace el commit para todos los archivos que han sido modificados o elminados,
        en caso de tener archivos nuevos primero debemos agregarlos con <pre> git add </pre>.

        <h3>Cómo enviar el código al repositorio remoto.</h3>

            <p>Para enviar nuestros cambios debemos escribir el comando:</p>
            <pre> git push </pre></p>

        <h3>Cómo configurar el origen del repositorio remoto para evitar escribirlo siempre cada vez que se hace un push o un pull.</h3>

            <p>Para configurar el origen debemos usar <pre> git remote add repository_url </pre>, 
            despues de esto solo queda configurar el upstream con el comando <pre> git push -u origin branch</pre>.</p>

        <h3>Diferencia entre un reset y revert.</h3>

            <p>git revert crea un nuevo commit que deshace los cambios del anterior commit. 
            Y git reset borra los cambios de los commits anteriores y el historial, y desplaza el HEAD al commit direccionado</p>

        <h3>Además de cambiar de ramas, para qué más se puede utilizar elcomando git checkout.</h3>

            <p>El comando checkout se puede utilizar para actualizar el arbol con los archivos correspondan al indice o al arbol especificado, de igual forma podemos crear branchs pasandole como argumento la flag -b,
            un string y este creara una nueva branch nombrada como el string pasado.</p>

        <h3>Como puede ver los commits que se han realizado en el proyecto.</h3>

            <p>Con solo utilizar el comando <pre> git log</pre> mostrara todos los commit, pero debe tener en cuenta que si la lista es 
            muy larga solo mostrara los mas nuevos para ver los mas antiguos debe recorrer el log y para salir de estos solo con escribir q se cerrara el log.</p>

        <h3>He modificado dos archivos y quiero hacer un commit por cadauno de ellos, ¿cómo lo puedo hacer?</h3>

            <p>agregando primero uno de los archivos a stagin luego creando un commit para este. Despues se repite el proceso para el otro archivos</p>

        <pre>
        git add first_file
        
        git commit -m "first file commit"</pre>


        <a href="/">Back to Home Page</a>
        </div>
    </body>
</html>

app/views/app/home.html.erb
<% provide(:title, "Home") %>
<!DOCTYPE html>

<html>
    <head>
        <title> <%= yield(:title) %> </title>
    </head> 

    <body>
        <div class="center jumbotron" >
            <br><h2 class="titulo">Home</h2><br>
            
            <div class="imgcontainer">
                <h4>This is the home page</h4>
                <img alt="Rails logo" width="200px" src="https://cdn.learnenough.com/kitten.jpg">
                <p>Esta pagina es genial tiene un gato y todo!</p>
            </div>
        </div>
    </body>
</html>

app/views/app/ruby.html.erb
<% provide(:title, "Ruby") %>
<!DOCTYPE html>
<html>
    <head>
        <title><%= yield(:title) %> </title>
    </head>

    <body>
        <div class="center jumbotron">
        <br><h2 class="titulo">Ruby</h2><br>

        <h3>Interpolación de strings</h3>

            <p>Para la interpolacion de string se pueden usar las siguientes formas:</p>
            <pre>
            #Definimos strings
            first_name = "Miguel"
            second_name = "Angel"

            #Interpolamos
            "first_name " + "last_name"
            -> Miguel Angel </pre>

        <h3>Cómo se declara un array y cómo se adiciona un elemento al final del array.</h3>

            <p>Para definir un array se puede hacer de la siguiente manera: </p>
            <pre>
            # Mediante el uso de []
            array = [element, element, element, ...]
            ->[element, element, element, ...]

            # Mediante el uso de el metodo split()
            "tres tristes tigres".split(" ")
            ->[tres, tristes, tigre] </pre>

            <p>Para insertar un elemento al final del array, se utiliza: </p>
            <pre>
            array.push(element)

            array << element] </pre>

        <h3>Cómo se itera un array utilizando el comando each.</h3>

            <p>Para la interpolacion de string se pueden usar las siguientes formas:</p>
            <pre>
            #Con solo each
            [1,2,3,4].each {|i| puts i}      #Con este codigo usando block nos imprime los numeros del 1 al 4

            #Usando each y do 
            [1,2,3,4].each do |i|            
            puts i  </pre>                  

        <h3>Cómo se declara un hash.</h3>

            <p>Lo puedes hacer de las siguientes maneras:</p>
            <pre>
            comida = hash.new
            comida = { desayuno: 'Huevos fritos', almuerzo: 'Lasagna', postre: 'Pastel' }
            comida = { :desayuno => 'Huevos fritos', :almuerzo => 'Lasagna', :postre => 'Pastel' }  </pre>

        <h3>Cómo se itera un hash utilizando el comando each.</h3>

            <p>Para iterar un hash usamos "key" y "value", el "key" puede ser el nombre del elemento y el "value" el valor de ese elemento. </p>
            <pre>
            comida.each { |key, value| puts "#{key}: #{value}" } </pre>

        <h3>¿Qué es un block en ruby? De un ejemplo de cómo utilizarlo.</h3>

            <p>Un block en ruby es una funcion anonima pasado a metodos pueden estar entre {} o entre do / end y los argumentos van entre pipes "|"
            ejemplo:</p>
            <pre>
            (1..5).each { |i| puts 2 * i }
            -> 2
            -> 4
            -> 6
            -> 8
            -> 10</pre>

        <h3>¿Cuál es la convención en Ruby a la hora de nombrar variables?</h3>

            <p>
            Debe estar en minusculas<br>
            No empezar con ningun caracter especial<br>
            Si contiene multiples palabras, separarlas por (_)<br>
            Evitar variables de un caracter<br>
            Variables descriptivas<br></p>
        
            <pre>first_name = 'fernando'</pre>

        <h3>¿Qué son attrreader, attrwriter y attraccesor?¿Para qué sirven?</h3>

        <p>Para exponer instancias de clase fuera de la clase se utilizan los attr_accesor, attr_reader, attr_writer.
        Estos son shortcuts que permiten crear metodos que crean los setter y getter el metodo.<br><br>

        El attr_accesor permite escribir y obtener datos.<br>
        El attr_reader permite solo leer datos.<br>
        El attr_writer permite solo escribirlos.<br>
        </p>

        <a href="/">Back to Home Page</a>
        </div>
    </body>
</html>

app/views/app/testing.html.erb
<% provide(:title, "Testing") %>
<!DOCTYPE html>
<html>
    <head>
        <title><%= yield(:title) %> </title>
    </head>

    <body>
        <div class="center jumbotron">
            <br><h2 class="titulo">Testing</h2><br>
            <p>
            This is the testing page for the
            <a href="https://www.railstutorial.org/">Ruby on Rails Tutorial</a>
            sample application.
            </p>

            <a href="/">Back to Home Page</a>
        </div>
    </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <header class="navbar navbar-fixed-top navbar-inverse"> 
    
    <nav> 
    
    <div class="tcontainer">
      <div class="clock">
        <%= Time.now %>
      </div>

      <div class="navlist">
        <ul class="nav navbar-nav navbar-right">
          <li> <%=link_to "Home", root_path %></li>
          <li> <%= link_to 'Basics', basics_path %>
          <li> <%=link_to 'Ruby', ruby_path %></li>
          <li> <%=link_to 'Git', git_path %></li>
          <li> <%=link_to 'Testing', testing_path %></li>
        </ul>
      </div>
    </div>
    </nav>
    </header>

    <div class="container">
      <%=yield%> 
    </div>
  </body>
</html>